name: Deploy

on:
  push:
    branches:
      - default

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish site
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: .
          fqdn: https://ns.u-wave.net
          keep_history: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
